image:
  # -- Registry & repo prefix for all images
  regRepo: ghcr.io/benc-uk
  # -- Set the image pull policy
  pullPolicy: Always
  # -- Tag for all images
  tag: latest
  # -- Image pull secrets if needed
  pullSecrets: []

# -- Enable authentication with an Azure AD app id
authClientId:

api:
  # -- Number of pod replicas for the API
  replicaCount: 1
  # -- Type of service for the API
  serviceType: ClusterIP
  
runner:
  # -- Number of pod replicas for the runner, best left as 1
  replicaCount: 1
  # -- How often to check for new & changed monitors in the database
  monitorChangeInterval: 120s
  alerting:
    # -- SMTP password for sending alerts, set to enable alerting
    password:
    # -- The email address to send alerts from, set to enable alerting
    from:
    # -- The email address to send alerts to, set to enable alerting
    to:
    # -- SMTP host for sending alerts
    smtpHost: smtp.gmail.com
    # -- SMTP port for sending alerts
    smtpPort: 587
    # -- How many times a monitor can fail before sending an alert
    failCount: 3

frontend:
  # -- Number of pod replicas for the frontend host
  replicaCount: 1
  # -- Type of service for the frontend
  serviceType: ClusterIP
  # -- Endpoint to access the deployed API, don't set when using ingress
  apiEndpoint:

mongodb:
  # -- Point to an existing MongoDB instance, leave blank when enabled=true
  connectionURI: 
  # -- Enable deploying MongoDB, leave connectionURI blank if true
  enabled: true
  #@ignored
  architecture: standalone
  #@ignored
  useStatefulSet: true
  persistence:
    # -- Enable persistence for MongoDB
    enabled: false
    # -- Size of the MongoDB persistent volume
    size: 1Gi
    # -- Storage class for the MongoDB persistent volume
    storageClass: default
  #@ignored
  auth:
    #@ignored
    enabled: false

ingress:
  # -- Use a Ingress, you will need an ingress controller deployed and setup
  enabled: false
  # -- Class name of your ingress controller
  className: "nginx"
  # -- Annotations applied to the ingress
  annotations: {}
  # -- Hostname for the ingress rules, strongly recommended to set
  host: 
  # -- TLS cert secret name, leave blank to disable TLS
  tlsSecret: 

# -- Annotations applied to all pods
podAnnotations: {}

# -- Node selector for all pods
nodeSelector: {}

# -- Tolerations used by all pods
tolerations: []

# -- Affinity used by all pods
affinity: {}

# -- Override the chart name
nameOverride: ""

# -- Override the full release name
fullnameOverride: ""
