{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nanomon.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nanomon.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tlsSecret }}
  tls:
  - hosts: 
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-api
            port:
              number: 80              
{{- end }}
