{{- if or .Values.runner.alerting.password .Values.mongodb.connectionURI -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nanomon.fullname" . }}
type: Opaque
data: 
  {{- if .Values.runner.alerting.password }}
  smtpPassword: {{ .Values.runner.alerting.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.connectionURI }}
  mongoURI: {{ .Values.mongodb.connectionURI | b64enc | quote }}
  {{- end }}
{{- end -}}