apiVersion: v1
entries:
  nanomon:
  - apiVersion: v2
    appVersion: 0.0.8
    created: "2023-10-28T11:03:16.084451395+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 6269c725121a3601e1fbb757d4c23ab2fb7eeb0d70ab1d09161bc416cd534f3a
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2023-10-28T11:03:16.077647567+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 548017dc70b65e20f85b8b231a52c8c7d67c6da231c1e413bc05d2ad95c43d6f
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2023-10-28T11:03:16.071528116+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 0b4e8fc35089d0bd7a327fcbb13c12d61a82fe5fe14e8bbf828cfb64826c9241
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.4.tgz
    version: 0.0.4
generated: "2023-10-28T11:03:16.066312772+01:00"
