apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanomon-api
spec:
  selector:
    matchLabels:
      app: nanomon-api
  template:
    metadata:
      labels:
        app: nanomon-api
    spec:
      containers:
      - name: nanomon-api
        image: ghcr.io/benc-uk/nanomon-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: MONGO_URI
            value: mongodb://mongo:27017
          - name: AUTH_CLIENT_ID
            value: 1751320d-d880-4d1c-92d5-d41eacef87bc            
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nanomon-api
spec:
  selector:
    app: nanomon-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
