apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nanomon.fullname" . }}-api
  labels:
    {{- include "nanomon.labels" . | nindent 4 }}
    component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "nanomon.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nanomon.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.regRepo }}/nanomon-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          env:
          - name: MONGO_URI
            {{ if .Values.mongodb.externalURI }}
            value: {{ .Values.mongodb.externalURI }}       
            {{ else }}
            value: "mongodb://{{ .Release.Name }}-mongodb"
            {{ end }}
            {{- if .Values.authClientId }}
          - name: AUTH_CLIENT_ID
            value: {{ .Values.authClientId }}
            {{- end }}            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
