apiVersion: v1
kind: Service
metadata:
  name: {{ include "nanomon.fullname" . }}-api
  labels: {{- include "nanomon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector: 
    {{- include "nanomon.selectorLabels" . | nindent 4 }}
    component: api
