apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nanomon.fullname" . }}-runner
  labels:
    {{- include "nanomon.labels" . | nindent 4 }}
    component: runner
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "nanomon.selectorLabels" . | nindent 6 }}
      component: runner
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nanomon.selectorLabels" . | nindent 8 }}
        component: runner
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.regRepo }}/nanomon-runner:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MONGO_URI
            {{ if .Values.mongodb.externalURI }}
            value: {{ .Values.mongodb.externalURI }}       
            {{ else }}
            value: "mongodb://{{ .Release.Name }}-mongodb"
            {{ end }}
          {{- if .Values.runner.monitorChangeInterval }}
          - name: MONITOR_CHANGE_INTERVAL
            value: {{ .Values.runner.monitorChangeInterval | quote }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
