name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build
        run: make build

      - name: Linting of Go code
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./services
  images:
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Build images
        env:
          IMAGE_TAG: dev
          VERSION: dev
          BUILD_INFO: "CI build, SHA:${{ github.sha }}"
        if: github.ref == 'refs/heads/main'
        run: make images

      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: make push
