name: Release Images

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"
        type: string

env:
  # Use the release tag
  IMAGE_TAG: ${{ github.event.release.tag_name || github.event.inputs.version }}
  VERSION: ${{ github.event.release.tag_name || github.event.inputs.version }}
  BUILD_INFO: "Stable build ${{ github.event.created_at }}"

permissions:
  packages: write

jobs:
  image-build:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo VERSION |$VERSION| and IMAGE_TAG |$IMAGE_TAG| and BUILD_INFO |$BUILD_INFO|
      # - name: Build images
      #   run: make images

      # - name: Push images
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      #     make push
